[project]
name = "schultz"
version = "0.1.0"
description = "Django Starter"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2",
    "django-environ>=0.12.0",
    "psycopg[binary]>=3",
]

[dependency-groups]
dev = [
    "ruff",
]
